package com.thelightphone.sdk

internal object LightSdkRegistry {

    private val generated by lazy {
        val clazz = Class.forName("com.thelightphone.sdk.generated.LightSdkRegistry")
        clazz.getField("INSTANCE").get(null)
    }

    @Suppress("UNCHECKED_CAST")
    val initialScreenFactory: ((SealedLightActivity) -> SimpleLightScreen<*>)? by lazy {
        generated::class.java.getMethod("getInitialScreenFactory").invoke(generated)
            as? (SealedLightActivity) -> SimpleLightScreen<*>
    }

    val entryPoint: LightEntryPoint? by lazy {
        generated::class.java.getMethod("getEntryPoint").invoke(generated) as? LightEntryPoint
    }

    @Suppress("UNCHECKED_CAST")
    val jobs: Map<String, LightJobHandler> by lazy {
        (generated::class.java.getMethod("getJobs").invoke(generated)
            as? Map<String, LightJobHandler>) ?: emptyMap()
    }
}
