[tool]
id = "com.zacksimpson.verses"
label = "Verses"
versionCode = 1
versionName = "1.0"
permissions = ["android.permission.INTERNET"]
# change if you run this on an LP3!
# serverPackage = "com.lightos"
serverPackage = "com.thelightphone.sdk.emulator"
