[tool]
id = "com.zacksimpson.verses"
label = "Verses"
versionCode = 2
versionName = "0.2.0"
permissions = ["android.permission.INTERNET"]
# change if you run this on an LP3!
# serverPackage = "com.lightos"
serverPackage = "com.thelightphone.sdk.emulator"
